import "@/styles/globals.css";
import { BlurredBackground, Header } from "@/components";

import { jetbrainsMono, roboto } from "@/lib/fonts";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang="pt-BR"
      className={`${roboto.variable} ${jetbrainsMono.variable} font-sans`}
    >
      <body>
        <Header />
        <BlurredBackground
          variant={"blue"}
          position={{
            top: "10%",
            left: "60%",
          }}
        />
        <BlurredBackground
          variant={"orange"}
          position={{
            top: "30%",
            left: "10%",
          }}
        />
        {children}
      </body>
    </html>
  );
}
